version: '3'

volumes:
  datamongo: {}
  dataelasticsearch: {}

services:
  elasticsearch:    
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    volumes:
      - dataelasticsearch:/usr/share/elasticsearch/data
      - ./logs/elasticsearch:/var/log/elasticsearch      
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.ml.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536  


  mongodb:   
    image: mongo:4.2
    volumes:
      - datamongo:/data/db  
      - ./logs/mongodb:/var/log/mongodb            

  gateway:
    image: graviteeio/gateway:latest
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_ratelimit_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_reporters_elasticsearch_endpoints_0=http://elasticsearch:9200            
    ports:
      - "8000:8082"
    volumes:
      - ./logs/gateway:/etc/gravitee.io/log
    depends_on:
      - mongodb
      - elasticsearch


  managementui:
    image: graviteeio/management-ui:latest
    environment:     
      - MGMT_API_URL=http:\/\/localhost:8005\/management\/
    ports:
      - "8002:80"
    volumes:
      - ./logs/management-ui:/var/log/httpd
    depends_on:
      - managementapi


  managementapi:
    image: graviteeio/management-api:latest
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_analytics_elasticsearch_endpoints_0=http://elasticsearch:9200
    ports:
      - "8005:8083"
    volumes:
      - ./logs/management-api:/home/gravitee/logs
    depends_on:
      - mongodb
      - elasticsearch
    environment:
      - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - gravitee_analytics_elasticsearch_endpoints_0=http://elasticsearch:9200                            


